hello guys This file contains the DB related script..
this  line was updated...
this line also updated second time ....
updated in dev branch..
<<<<<<< HEAD
=======
updated in state branch...
ufff another time also updated this branch...

>>>>>>> 162b2b3 (added)
